Module6 task1
htmlacademy-yii/1367633-task-force-1 pull request #13
Opened 2020-11-28 09:39 UTC by nazaryuzhyn

2020-11-30 06:20 UTC, nikserg requested changes
Отлично! Есть несколько архитектурных замечаний по улучшению.

2020-11-30 06:20 UTC, nikserg commented on frontend/controllers/TasksController.php
> +		$categories = Category::find()->all();
Если тебе нужен только id и name, можно добавить в конструктор запроса ->select('id', 'name')

2020-11-30 06:20 UTC, nikserg commented on frontend/controllers/TasksController.php
> +			if ($taskForm->category) {
Обычно конструктор запроса по переданным параметрам засовывают в метод search() модели.

2020-11-30 06:20 UTC, nikserg commented on frontend/controllers/TasksController.php
> +		$tasks = $tasks->all();
В ТЗ есть пункт:
"На странице показывается максимум пять заданий. При большем числе записей следует показывать их через пагинацию."
Пагинацию будешь позже делать?

2020-11-30 06:20 UTC, nikserg commented on frontend/controllers/UsersController.php
> +			if ($userForm->category) {
Замечания относительно конструктора запросов аналогичны таковым для списка задач.

2020-12-06 06:26 UTC, nazaryuzhyn commented on frontend/controllers/TasksController.php
> +		$categories = Category::find()->all();
Понял, ok

2020-12-06 06:26 UTC, nazaryuzhyn commented on frontend/controllers/TasksController.php
> +			if ($taskForm->category) {
Сделал

2020-12-06 06:28 UTC, nazaryuzhyn commented on frontend/controllers/TasksController.php
> +		$tasks = $tasks->all();
Буду делать пагинацию, я просто думал это будет отдельное задание

2020-12-06 06:28 UTC, nazaryuzhyn commented on frontend/controllers/UsersController.php
> +			if ($userForm->category) {
Сделал

2020-12-07 06:09 UTC, nikserg requested changes

2020-12-07 06:09 UTC, nikserg commented on frontend/models/requests/TaskForm.php
> +	public function search()
Не совсем правильно понял мое замечание. Метод search() должен возвращать объект Query, у которого уже можно вызвать ->all() или другой метод получения данных, либо добавить еще условий. Так достигается дополнительная гибкость. Иными словами, последняя команда перед return в этом методе лишняя.

2020-12-07 06:18 UTC, nazaryuzhyn commented on frontend/models/requests/TaskForm.php
> +	public function search()
Вроде сделал

2020-12-09 14:56 UTC, merged