Публикация
htmlacademy-yii/1367633-task-force-1 pull request #17
Opened 2021-01-17 08:09 UTC by nazaryuzhyn

2021-01-18 06:48 UTC, nikserg requested changes
Ошибок нет, но есть замечания по улучшению. Посмотри, пожалуйста, если найдешь полезными - используй.

2021-01-18 06:48 UTC, nikserg commented on frontend/controllers/TasksController.php
> +			'matchCallback' => function ($rule, $action) {
Это не ошибка, но matchCallback прямо в контроллере - это, по сути, пространство для костыля. Использовать его таким образом не желательно. Подумай о том, чтобы переопределить класс AccessControl для проверки роли. Приведу небольшой код из реального проекта, подумай об этом. Там переопределяется denyCallback, но суть та же самая.

 ```
public function behaviors()
    {
        return [
            'confirmPhone' => [
                'class' => ConfirmPhoneFilter::class,
            ],
            'access'       => [
                'class' => AccessControl::class,
                'only'  => ['index', 'request', 'frame'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }
```


```
class AccessControl extends \yii\filters\AccessControl {

    public function __construct($config = [])
    {
        $this->denyCallback = function($rule, Action $action) {
            return $action->controller->redirect(\Yii::$app->urlManager->createUrl(['site/login', 'redirect' => \Yii::$app->request->url]));
        };
        parent::__construct($config);
    }
}
```

2021-01-18 06:48 UTC, nikserg commented on frontend/controllers/TasksController.php
> +				$task->save();
Тут желательно проверять на ошибки при сохранении.

2021-01-19 09:29 UTC, nazaryuzhyn commented on frontend/controllers/TasksController.php
> +			'matchCallback' => function ($rule, $action) {
Переделал

2021-01-19 09:29 UTC, nazaryuzhyn commented on frontend/controllers/TasksController.php
> +				$task->save();
Сделал

2021-01-20 08:09 UTC, merged