Module1 task3
htmlacademy-yii/1367633-task-force-1 pull request #5
Opened 2020-09-23 15:53 UTC by nazaryuzhyn

2020-09-24 08:04 UTC, nikserg requested changes
Небольшие изменения по неймингу.

2020-09-24 08:04 UTC, nikserg commented on composer.json
> +    "name": "task-force/vendor",
Правильный нейминг - <разработчик>/<пакет>. В этом случае можно что-нибудь типа nazaryuzhyn/task-force

2020-09-24 08:04 UTC, nikserg commented on index.php
> +	require_once 'vendor/autoload.php';
Не вижу пока необходимости в файле index.php. Пусть будет только test.php

2020-09-24 08:04 UTC, nikserg commented on src/classes/Task.php
> +	namespace TaskForce\classes;
Неймспейсы лучше именовать по смыслу. Например, Task-это модель, ее можно положить в неймспейс models.

2020-09-24 08:23 UTC, nazaryuzhyn commented
Сделал!

2020-09-24 08:30 UTC, nazaryuzhyn commented on index.php
> +	require_once 'vendor/autoload.php';
Как лучше подключать? require_once 'vendor/autoload.php'; или require_once __DIR__ . '/vendor/autoload.php';

2020-09-24 08:33 UTC, nikserg commented on index.php
> +	require_once 'vendor/autoload.php';
Лучше использовать `__DIR__`

2020-09-24 08:35 UTC, nazaryuzhyn commented on index.php
> +	require_once 'vendor/autoload.php';
Понял, спасибо

2020-09-28 06:22 UTC, nikserg requested changes
Нужно добавить тесты.

2020-09-28 06:22 UTC, nikserg commented on test.php
> +	require_once __DIR__ . '/vendor/autoload.php';
А где сам тест? Там нужно вызвать несколько методов класса и проверить их результат.

2020-09-28 07:05 UTC, nazaryuzhyn commented on test.php
> +	require_once __DIR__ . '/vendor/autoload.php';
Сделал

2020-09-29 07:20 UTC, nazaryuzhyn commented on test.php
> +	require_once __DIR__ . '/vendor/autoload.php';
То что я сделал подходит? Можно отправлять на проверку?

2020-09-29 08:25 UTC, nikserg commented on test.php
> +	require_once __DIR__ . '/vendor/autoload.php';
Подходит, если тест у тебя проходит успешно. Отправляй в любом случае, иначе я не увижу уведомления о твоем комментарии. Сейчас случайно нашел.

2020-09-29 08:27 UTC, nazaryuzhyn commented on test.php
> +	require_once __DIR__ . '/vendor/autoload.php';
Проходит успешно. Отправил на проверку

2020-09-29 08:31 UTC, merged