Module2 task1
htmlacademy-yii/1367633-task-force-1 pull request #6
Opened 2020-09-30 16:22 UTC by nazaryuzhyn

2020-10-02 10:51 UTC, nikserg requested changes
Прокомментировал некоторые моменты по структуре БД.

2020-10-02 10:51 UTC, nikserg commented on schema.sql
> +	CONSTRAINT `category_ibfk_1` FOREIGN KEY (`id`) REFERENCES `task` (`category_id`)
Обычно внешние ключи приянто именовать как `fk_<таблица>_<столбец>(_<целевая таблица>_<столбец>)?`
Ты делал схему с помощью Mysql Workbench?

2020-10-02 10:51 UTC, nikserg commented on schema.sql
> +	`city` varchar(255) not null,
Если это название, логично назвать столбец name

2020-10-02 10:51 UTC, nikserg commented on schema.sql
> +CREATE TABLE IF NOT EXISTS `favorite` (
Это что за механизм "избранного"? Что именно можно в него добавить?

2020-10-02 10:51 UTC, nikserg commented on schema.sql
> +	`file` text not null,
`text` будет многовато, достаточно varchar(255). А ты не хочешь избавиться от хранения записей о файлах в БД?

2020-10-02 10:51 UTC, nikserg commented on schema.sql
> +	`new_message` tinyint(1) unsigned not null,
Это тип уведомления? Может, проще все схлопнуть в одно поле `type`?

2020-10-02 10:51 UTC, nikserg commented on schema.sql
> +	`date_created` timestamp not null default CURRENT_TIMESTAMP,
Лучше дату по умолчанию реализовать средствами Yii. Там есть такая штука как TimestampBehaviour

2020-10-02 10:51 UTC, nikserg commented on schema.sql
> +	CONSTRAINT `reviews_ibfk_1` FOREIGN KEY (`task_id`) REFERENCES `task` (`id`)
На customer_id и implementer_id тогда уж тоже нужны внешние ключи

2020-10-02 10:51 UTC, nikserg commented on schema.sql
> +CREATE TABLE IF NOT EXISTS `specialisation` (
specialization

2020-10-02 10:51 UTC, nikserg commented on schema.sql
> +	`status` enum('new','processing','performed','failed','canceled') not null default new,
Ограничения на допустимые значения лучше делать на уровне приложения, а не БД

2020-10-02 10:51 UTC, nikserg commented on schema.sql
> +	`longitude` decimal(10,7) not null,
Нам нужны координаты таски? Города недостаточно?

2020-10-02 10:51 UTC, nikserg commented on schema.sql
> +	`password` varchar(255) not null,
Для хэша пароля достаточно длины 64

2020-10-02 10:51 UTC, nikserg commented on schema.sql
> +	`role` enum('customer','implementer') not null default customer,
Аналогично, enum

2020-10-02 10:51 UTC, nikserg commented on schema.sql
> +	`photo` varchar(255) not null,
Может, завязать на таблицу file, коль скоро ты хранишь данные о файлах в БД?

2020-10-02 10:51 UTC, nikserg commented on schema.sql
> +CREATE TABLE IF NOT EXISTS `chat` (
У тебя здесь хранятся сообщения чата, может, назвать таблицу chat_message?

2020-10-02 10:51 UTC, nikserg commented on schema.sql
> +CREATE TABLE IF NOT EXISTS `user` (
Насколько я помню, для пользователя там были еще настройки уведомлений. Их тоже надо в базе хранить.

2020-10-02 11:13 UTC, nazaryuzhyn commented on schema.sql
> +	CONSTRAINT `category_ibfk_1` FOREIGN KEY (`id`) REFERENCES `task` (`category_id`)
Схему делал где то онлайн, на каком то сайте

2020-10-02 12:07 UTC, nazaryuzhyn commented on schema.sql
> +	`new_message` tinyint(1) unsigned not null,
Это уведомления с настроек профиля пользователя

2020-10-02 13:44 UTC, nazaryuzhyn commented on schema.sql
> +	CONSTRAINT `category_ibfk_1` FOREIGN KEY (`id`) REFERENCES `task` (`category_id`)
Переименовал ключи

2020-10-02 13:44 UTC, nazaryuzhyn commented on schema.sql
> +	`city` varchar(255) not null,
Сделал!

2020-10-02 13:50 UTC, nazaryuzhyn commented on schema.sql
> +CREATE TABLE IF NOT EXISTS `favorite` (
Пользователи, которые были добавлены в избранное

2020-10-02 13:53 UTC, nazaryuzhyn commented on schema.sql
> +	`file` text not null,
Каким образом это можно сделать?

2020-10-02 13:59 UTC, nazaryuzhyn commented on schema.sql
> +	`longitude` decimal(10,7) not null,
В тз пишет что нужно

2020-10-02 14:01 UTC, nazaryuzhyn commented on schema.sql
> +CREATE TABLE IF NOT EXISTS `user` (
Эти уведомления у меня в таблице notification

2020-10-06 06:51 UTC, nikserg commented on schema.sql
> +	`file` text not null,
Например, именовать файлы по ID сущности. Например, у тебя есть аватарки пользователей. Создаем папку user_avatars и кладем туда файл 1.jpg - это будет аватарка пользователя с ID 1. И так далее.

2020-10-06 06:51 UTC, nikserg commented on schema.sql
> +	`new_message` tinyint(1) unsigned not null,
Тогда эти настройки стоит перенести в таблицу с пользователями как отдельные флаги.

2020-10-06 06:51 UTC, nikserg commented on schema.sql
> +	`password` varchar(255) not null,
?

2020-10-06 06:51 UTC, nikserg commented on schema.sql
> +	`role` enum('customer','implementer') not null default customer,
?

2020-10-06 06:52 UTC, nikserg commented on schema.sql
> +	`photo` varchar(255) not null,
?

2020-10-06 06:52 UTC, nikserg commented on schema.sql
> +CREATE TABLE IF NOT EXISTS `chat` (
?

2020-10-06 06:52 UTC, nikserg commented on schema.sql
> +CREATE TABLE IF NOT EXISTS `user` (
Лучше оставить в таблице user.

2020-10-06 06:53 UTC, nikserg commented
Не все комментарии отвечены, плюс добавил еще замечаний.

2020-10-06 06:59 UTC, nazaryuzhyn commented on schema.sql
> +	`new_message` tinyint(1) unsigned not null,
Сделал

2020-10-06 07:01 UTC, nazaryuzhyn commented on schema.sql
> +	`date_created` timestamp not null default CURRENT_TIMESTAMP,
+

2020-10-06 07:01 UTC, nazaryuzhyn commented on schema.sql
> +	CONSTRAINT `reviews_ibfk_1` FOREIGN KEY (`task_id`) REFERENCES `task` (`id`)
+

2020-10-06 07:01 UTC, nazaryuzhyn commented on schema.sql
> +CREATE TABLE IF NOT EXISTS `specialisation` (
`+`

2020-10-06 07:02 UTC, nazaryuzhyn commented on schema.sql
> +	`status` enum('new','processing','performed','failed','canceled') not null default new,
`+`

2020-10-06 07:03 UTC, nazaryuzhyn commented on schema.sql
> +	`password` varchar(255) not null,
Сделал

2020-10-06 07:03 UTC, nazaryuzhyn commented on schema.sql
> +	`role` enum('customer','implementer') not null default customer,
Сделал

2020-10-06 07:05 UTC, nazaryuzhyn commented on schema.sql
> +	`file` text not null,
Хорошо, понял, так и сделаю, спасибо

2020-10-06 07:06 UTC, nazaryuzhyn commented on schema.sql
> +	`photo` varchar(255) not null,
Сделаю без хранение данных о файле в бд

2020-10-06 07:06 UTC, nazaryuzhyn commented on schema.sql
> +CREATE TABLE IF NOT EXISTS `chat` (
Сделал

2020-10-06 07:07 UTC, nazaryuzhyn commented on schema.sql
> +CREATE TABLE IF NOT EXISTS `user` (
Сделал

2020-10-07 06:48 UTC, nikserg commented
Конфликты в composer.json. Нужно залить вначале ветку master в рабочую ветку, чтобы разрешить конфликты. Если будут трудности с этим - пиши в Телеграм.

2020-10-07 10:10 UTC, merged