Module2 task2
htmlacademy-yii/1367633-task-force-1 pull request #7
Opened 2020-10-09 14:34 UTC by nazaryuzhyn

2020-10-14 08:25 UTC, nikserg requested changes
Код рабочий, но есть замечания по оформлению.

2020-10-14 08:25 UTC, nikserg commented on src/Actions/AbstractAction.php
> +		abstract public function nextStatus();
Везде комменты есть, а тут почему-то нету 🤔

2020-10-14 08:25 UTC, nikserg commented on src/Actions/CancelAction.php
> +	class CancelAction extends AbstractAction
Коммент для класса тоже нужен.

2020-10-14 08:25 UTC, nikserg commented on src/Actions/AbstractAction.php
> +		abstract public function getUser($idCustomer, $idImplementer, $idUser);
Если речь идет о проверке чего-либо, обычно название функции начинают с is или check или can. В данном случае, думаю, стоит использовать что-нибудь вроде checkRight или canUse.

2020-10-14 08:25 UTC, nikserg commented on src/models/Task.php
> +					if($action->getUser($this->idCustomer, $this->idImplementer, $idUser)){
Не очень корректное форматирование кода, в плане отступов, пробелов, переносов строк. Если используешь IDE PhpStorm, попробуй комбинацию клавиш Ctrl+Shift+L - это автоматическое выравнивание кода.

2020-10-14 12:53 UTC, nazaryuzhyn commented on src/Actions/AbstractAction.php
> +		abstract public function nextStatus();
Сделал

2020-10-14 13:09 UTC, nazaryuzhyn commented on src/Actions/CancelAction.php
> +	class CancelAction extends AbstractAction
Сделал

2020-10-14 13:22 UTC, nazaryuzhyn commented on src/Actions/AbstractAction.php
> +		abstract public function getUser($idCustomer, $idImplementer, $idUser);
Сделал

2020-10-14 13:27 UTC, nazaryuzhyn commented on src/models/Task.php
> +					if($action->getUser($this->idCustomer, $this->idImplementer, $idUser)){
Использую vs code, сделал автоматическое выравнивание кода

2020-10-15 06:43 UTC, nikserg requested changes
Добьем немного оформление кода и готово!

2020-10-15 06:43 UTC, nikserg commented on src/models/Task.php
> +		$ActionAvailable = [];
Название переменных по camelCase должно всегда начинаться со строчной буквы. В этом случае - `actionAvailable`

2020-10-15 06:43 UTC, nikserg commented on src/Actions/AbstractAction.php
> +		 * @param [int] $idCustomer
А почему типы переменных в квадратных скобках? Это IDE так подсказывает? Насколько я знаю, по стандарту допускается только без скобок.

2020-10-15 06:43 UTC, nikserg commented on src/Actions/AbstractAction.php
> +		 * @return true если у пользователя есть право на действие
Желательно тип возвращаемого значения тоже указывать.
`* @return bool true если у пользователя есть право на действие`

2020-10-15 07:16 UTC, nazaryuzhyn commented on src/models/Task.php
> +		$ActionAvailable = [];
Сделал

2020-10-15 07:19 UTC, nazaryuzhyn commented on src/Actions/AbstractAction.php
> +		 * @param [int] $idCustomer
Сделал без скобок

2020-10-15 07:20 UTC, nazaryuzhyn commented on src/Actions/AbstractAction.php
> +		 * @return true если у пользователя есть право на действие
Сделал

2020-10-20 14:25 UTC, merged